### ISSUE TITLE
Brokens bullet point lists on warnings.html page

### ISSUE THREAD

**Issue by kaybenleroll** [stan-dev/stan-dev.github.io#107]
Under each of the entries for the various stan https://github.com/stan-dev/stan-dev.github.io/issues/27warnings are some bullet point list entries.

The bullet points in the Rmd file need to be indented by some whitespace. I have made these edits but I am not sure what the convention is for pull requests. Let me know and I'm happy to submit it since it is a minor edit.

**Comment by mitzimorris** [comment]
I fixed the file `misc/warnings.Rmd` and renamed it to `warnings.md`.
