### ISSUE TITLE
Add NIPS page

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan-dev.github.io#12]
@betanalpha @akucukelbir, put up a page for NIPS.

Could you toss on a Stan at NIPS schedule on there too?

**Comment by akucukelbir** [comment]
@betanalpha can i just start pushing to master? (i won't link anything to the rest of the website yet.)

**Comment by betanalpha** [comment]
I have a draft in preparation that'll lost after I get back from dinner.  If you have anything you want to add besides the talk schedules just send me the text in an email.

**Comment by akucukelbir** [comment]
ok, cheers. let me know when you push.

**Comment by betanalpha** [comment]
http://mc-stan.org/misc/nips2015.html

Feel free to go ahead and push to master with any changes.

**Comment by dustinvtran** [comment]
I’ll be at the approximate inference and black box learning workshops as well. (a talk at the black box learning on new variational inference stuff, and a contributed talk at the approximate inference)

Dustin

**Comment by dustinvtran** [comment]
(i pushed changes to master)

Dustin

**Comment by betanalpha** [comment]
Just a note that we're restricting the announcement to Stan-related talks or talks by Stan devs.  I've pushed what should be a near-final version.  @akucukelbir feel free to add links to install instructions as you need.

**Comment by akucukelbir** [comment]
@betanalpha dave and rajesh's talks involve ADVI (and Stan in general, actually). i'd like to add them back. 

re instructions: i'll add those towards the end of the week.

the formatting changes look good. i like them.

**Comment by betanalpha** [comment]
> @betanalpha dave and rajesh's talks involve ADVI (and Stan in general, actually). i'd like to add them back.
> 

This is the first we’ve heard of any such involvement!  Again, we’re just
trying to focus on Stan here and, in particular, Stan developers, and not
tangential connections.  Others can chime in with opinions.

**Comment by dblei** [comment]
this page looks great!  i think stan will receive a lot of positive attention at NIPS and hopefully the ML crowd will start widely using it.

i'm equally happy to be included in the page or not.  (e.g., restricting to stan developers seems like a perfectly sensible criterion.)

**Comment by betanalpha** [comment]
After discussing with Bob and Dan we have decided to remain strict with regards to
inclusion on this page.  We are including only Stan developers and may add any
speakers who are using Stan directly in their presented work (we’re not sure of any, 
but will ask around).  Ultimately we want to be careful for this page to focus on
promoting Stan.

I have also renamed the page from nips2015 to nips to make it easier for the
audience to copy.  

Please do not change the included speakers.
