### ISSUE TITLE
Spreadshirt links on Shop page are dead

### ISSUE THREAD

**Issue by BrandonEdwards** [stan-dev/stan-dev.github.io#145]
Both mc-stan.spreadshirt.com and mc-stan.spreadshirt.co.uk are dead links on https://mc-stan.org/shop/. 

I also could not find Stan at all on the Spreadshirt website to let me update the links on that page via a pull request, so perhaps we can no longer infer in style?

**Comment by WardBrian** [comment]
They seem to be working once again
