### ISSUE TITLE
A dead link in the documentation page

### ISSUE THREAD

**Issue by skumagai** [stan-dev/stan-dev.github.io#18]
In documentation page, the link to the first written tutorial returns 404.

Michael Clark. (2015) Bayesian Basics: A Conceptual Introduction with Application in R and Stan. Center for Statistical Consultation and Research, University of Michigan.

**Comment by bob-carpenter** [comment]
Thanks for pointing that out.  I found the link from the author's Google pages, so I updated our pages.
