### ISSUE TITLE
Developer Process Wiki is empty page

### ISSUE THREAD

**Issue by avehtari** [stan-dev/stan-dev.github.io#26]
stan-dev.github.io/development/index.md
says
"If you’d like to contribute code, please submit it through a Git pull request. The developer process for creating a Git pull request is described on the Stan Wiki."
and has link to "Developer Process Wiki" https://github.com/stan-dev/stan/wiki/Developer-Process
which produces a page saying "Create new page"
I couldn't find where the link should point to.

**Comment by syclik** [comment]
Thanks.
