### ISSUE TITLE
Page Titles feature Dangling Hyphen

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan-dev.github.io#3]
They're coming out as "Stan -" and "Documentation -" on Safari.

**Comment by bob-carpenter** [comment]
I'm confused.  Are we no longer using the old repo?  I filed exactly the same issue there:

https://github.com/stan-dev/webpages/issues/12

**Comment by bob-carpenter** [comment]
Can we merge so we just have one of these?

**Comment by betanalpha** [comment]
stan-dev/webpages is the old site, it has not been modified.
The new site lives in stan-dev/stan-dev.github.io — I moved
the issue to the new site, merged, and closed.

**Comment by bob-carpenter** [comment]
I think the titles should say "Stan: " or "Stan-" so it's clear
from browser tabs where you're at.

- Bob
