### ISSUE TITLE
Invalid TLS certificate

### ISSUE THREAD

**Issue by ariddell** [stan-dev/stan-dev.github.io#32]
I went to https://mc-stan.org/documentation/case-studies/grsm_latent_reg.html and got the following message:

```
mc-stan.org uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by bob-carpenter** [comment]
There is no such page, so it's hitting the "rejection" page.  No idea why that's causing problems other than the potential redirect.  The rest of the site looks OK.  I have no idea how to fix this as all of this is configured by GitHub, not by us.  We can check back and see if they iron out their error redirects, which may go through github.com or something and back.

**Comment by ariddell** [comment]
That's not such a big deal then. Bug against github, I guess.

**Comment by syclik** [comment]
Did you try with just http? I don't think GitHub Pages has https enabled.
I'm not sure if that's something we can do on our own.

**Comment by ariddell** [comment]
Wait, then this is a big issue. I'm getting the same warning with https://mc-stan.org/.

I think websites get dinged for not having https.

At some point this probably should be fixed.

Looks like Julia uses fastly to proxy the traffic. Might be relatively easy to setup.

https://github.com/JuliaLang/julia/issues/21078

**Comment by betanalpha** [comment]
Does it work if you go to stan-dev.github.io <http://stan-dev.github.io/> directly?
The mc-stan.org <http://mc-stan.org/> hosting may not handle certificates
correctly.

**Comment by ariddell** [comment]
There are no certificates for http. Yes, it works fine for http.

**Comment by bob-carpenter** [comment]
What does the proxy do?  

Why would people trust fastly's proxy of GitHub's http rather than GitHub's http directly?  (That wasn't a rhetorical question---I know pretty much zero about web protocols and safety.)

**Comment by ariddell** [comment]
The proxy just handles https traffic. It fetches the pages by http and then sends them to the user over https. You have to give the proxy your TLS certificate (or it will generate one for you). Github does not serve custom domains over https. (It's a known issue and github has marked it WONTFIX as far as I can tell. Pages like pagename.github.io work fine -- it's just custom domains that have the problem.)

**Comment by ariddell** [comment]
Here's the relevant github issue: isaacs/github#156

**Comment by randommm** [comment]
Suggestion: it is possible to use Let's Encrypt with custom domains for free on Gitlab. I tryed this myself and works perfectly.

**Comment by syclik** [comment]
See: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ (thanks @KOLANICH for the link)
