### ISSUE TITLE
links are broken, should have redirects

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan-dev.github.io#37]
All of the search on the site is broken from Google.  And any link that existed is now broken.  It's standard operating procedure in these cases to leave redirect links in place of the dead links.  Google's smart enough to index the new things.

**Comment by bnicenboim** [comment]
Sorry to hijack the thread, but you should think on adding DOIs to the case studies and the Stancon papers. If I want to refer to them in a paper, it's much better than to have a link (and journals usually ask for the DOIs).

**Comment by seantalts** [comment]
@bob-carpenter Which links? I noticed this and brought it up to Michael and he thought it was fine to leave the URLs all reorganized without redirects, so I added redirects myself to `/documentation/` and `/interfaces/` since those were getting 404s from my quick Google searches. What other URLs need this?

**Comment by bob-carpenter** [comment]
@bnicenboim:  Thanks for commenting, but in the future, please just open a new issue.  They're easier to close than it is for me to do what I'm going to do and open the issue myself:

https://github.com/stan-dev/stan-dev.github.io/issues/38

**Comment by bob-carpenter** [comment]
@seantalts --- it looks like Google's catching up.  Though why a search for `[stan manual]` for me pulls up a version 2.08 manual at U Minnesota is beyond me.  What in the world is Google thinking?

**Comment by bob-carpenter** [comment]
A search for `[site:mc-stan.org -discourse]` reveals the following 404s in 14 pages of hits, omitting 132 near duplicates (wonder if any of those are 404?):

* http://mc-stan.org/citations/

* http://mc-stan.org/issues/

* http://mc-stan.org/development/

* http://mc-stan.org/funding/

* http://mc-stan.org/documentation/case-studies/identifying_mixture_models.html

* http://mc-stan.org/documentation/case-studies/pcm_and_gpcm.html

* http://mc-stan.org/documentation/case-studies/hierarchical_2pl.html

* http://mc-stan.org/documentation/case-studies/divergences_and_bias.html

* http://mc-stan.org/bayesplot/plotting-mcmc-draws.html

* http://mc-stan.org/documentation/case-studies/rsm_and_grsm.html

* http://mc-stan.org/bayesplot/posterior-predictive-checking.html

* http://mc-stan.org/documentation/case-studies/curse-dims.html

* http://mc-stan.org/documentation/case-studies/mle-params.html

* http://mc-stan.org/documentation/case-studies/dorazio-royle-occupancy.html

* http://mc-stan.org/documentation/case-studies/pool-binary-trials.html

* http://mc-stan.org/documentation/case-studies/pool-binary-trials-rstanarm.html

Also, no idea what this is:

* http://mc-stan.org/tags/

* http://mc-stan.org/interfaces/stan

* http://mc-stan.org/interfaces/rstanarm

* http://mc-stan.org/interfaces/math

* http://mc-stan.org/interfaces/rstantools

* http://mc-stan.org/interfaces/loo

* http://mc-stan.org/bayesplot/references.html

* http://mc-stan.org/interfaces/julia-stan

* http://mc-stan.org/interfaces/mathematica-stan

* http://mc-stan.org/interfaces/stata-stan
