### ISSUE TITLE
/about/team never loads in Chrome-based browsers

### ISSUE THREAD

**Issue by seantalts** [stan-dev/stan-dev.github.io#40]
http://mc-stan.org/about/team/

**Comment by seantalts** [comment]
never mind! something weird was happening to my browser, I think.

**Comment by randommm** [comment]
I don't think it's just your browser. I'm also unable to correctly open the page http://mc-stan.org/about/team/ on Chromium or Google Chrome, just hangs and keeps eating the CPU forever (until Chromium automatically proposes to kill the page), if I wait long enough, it opens but does not load correctly (just keep scrolling more and more and "loading"). I traced down the problem to a main.css property:

`@media screen and (min-width: 62.5em){.dev-bio-photo{display:block;width:75px;height:75px;margin-right:25px;margin-bottom:10px;border-radius:150px;float:left}.dev-bio-photo:after{content:"";display:table;clear:both}}`

I works fine if I remove the `float:left` from the code above.

I was able to reproduce this on Docker (with https://hub.docker.com/r/marcoinacio/vncmate/).

Chromium version: Version 58.0.3029.110 Built on Ubuntu.
Also did not work with latest Official Google Chrome 59.0.3071.104
But seems to work fine on Firefox.

It's really odd, CSS shouldn't be able to do that.

**Comment by seantalts** [comment]
Ah ha! So I wasn't going crazy, thanks. I'll reopen this.

**Comment by bob-carpenter** [comment]
It opened OK in Safari for me, but it's *very* slow.

**Comment by bob-carpenter** [comment]
If you can figure out how to add more space between members that'd be great, because right now, they're running together.  The basic rule for typography is that lines of text that goes together as a group should have smaller inter-line spacing than the space between groups.

Also, it opens OK in Safari.

**Comment by seantalts** [comment]
(I have no idea how to do anything to do with CSS; not sure who set up the website or would know more about Jekyll styling)

**Comment by bob-carpenter** [comment]
OK, I can take a look.

**Comment by jgabry** [comment]
Not sure if this should be reopened but I'm now having trouble loading the team page on chrome. Anyone else?

**Comment by maverickg** [comment]
Neither could I load mc-stan.org/about/team/ now

**Comment by randommm** [comment]
The last band-aid-like solution didn't hold much longer, but this PR will (hopefully) fix it for good.
