### ISSUE TITLE
404 page: fermiac image doesn't show

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan-dev.github.io#42]
Hopefully the image shows.

![image](https://user-images.githubusercontent.com/425751/27441818-9e538ac0-573c-11e7-85ee-38f6d40acee4.png)

**Comment by betanalpha** [comment]
The image loads fine on Safari.  No idea why Chrome doesn't load it.

**Comment by syclik** [comment]
Yeah. Loads fine on my phone too. 

Any ideas on how to debug from within chrome?

**Comment by bbbales2** [comment]
It's a pdf (/images/ulam-fermiac.pdf). Probly just roll with a .jpg and it'll work?

**Comment by sakrejda** [comment]
Seems like some other image format is better for Chrome unless we require a
plugin: https://productforums.google.com/forum/#!topic/chrome/A3XrBbHD80U

**Comment by betanalpha** [comment]
Converted to a PNG.
