### ISSUE TITLE
workshops material missing

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan-dev.github.io#5]
Is there an easy way to move the workshops material over?  Or did you drop it on purpose?

**Comment by betanalpha** [comment]
I don’t think workshop material should be continuously
hosted on the website.  But if we do want to keep
workshop material up permanently we have to figure
out the format/procedure for adding more (and how
much space before GitHub yells at us).

**Comment by bob-carpenter** [comment]
OK.  I can host it on my own GitHub account.

- Bob

**Comment by syclik** [comment]
I'm closing this issue. It looks like we figured it out.
