### ISSUE TITLE
update NumFOCUS donation link

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan-dev.github.io#81]
From issue https://github.com/stan-dev/stan/issues/2743 originaly submitted by @lismartin72.  

----

Hi, I am a new staff member at NumFOCUS. We have updated our donation provider from Flipcause to Salsa. The new link is: 

https://numfocus.salsalabs.org/donate-to-stan/index.html

Please update your website accordingly. : )

Thanks, 

Lisa Martin
NumFOCUS

**Comment by breckbaldwin** [comment]
Done and tested.
