### ISSUE TITLE
add "bulk ess" and "tail ess" details to warnings page

### ISSUE THREAD

**Issue by ecmerkle** [stan-dev/stan-dev.github.io#84]
The new rstan 2.19.2 provides warnings about bulk ess and tail ess, and those warnings include the following links:

http://mc-stan.org/misc/warnings.html#bulk-ess
http://mc-stan.org/misc/warnings.html#tail-ess

But those sections of the page do not currently exist. It looks like the sections do exist in misc/warnings.Rmd, so maybe that Rmd just needs to be compiled to html?

**Comment by avehtari** [comment]
Thanks! We'll fix this

**Comment by avehtari** [comment]
Knitted to html and pushed
