### ISSUE TITLE
link broken on team page 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/stan-dev.github.io#9]
On the Team page under [Join the Development Team](http://mc-stan.org/team/#join-the-development-team) the link where is says "read about [how to contribute to Stan](http://mc-stan.org/contribute/)" seems to be broken (it points to a non-existent Contribute page). Is the intent to link to the github wiki or just to the "Development" page on the website?

**Comment by bob-carpenter** [comment]
I think it should point back into the site.  

I tried to set it up so that each outbound link was
unique so we would have extra nav, but no inconsistency
problems.

I like the off-site markers on the links and
PDFs, but it's not part of the Style Michael used.

- Bob
